- name: "Apache installation using docker"
  hosts: prod
  become: true
  pre_tasks:
  - name: install epel release
    yum:
      name: "{{ item }}"
      state: latest
    when: ansible_facts['os_family'] == "Redhat"
    loop:
      - epel-release
      - wget
      - git
  - name: install docker
    ansible.builtin.package:
      name: "{{ item }}"
    loop:
      - python-pip
      - python-setuptools
      - python-virtualenv
      - docker
      - python-docker-py
  - name: start docker engine
    ansible.builtin.systemd:
      state: started
      name: docker
  tasks:
  - name: Copy website file template
    template:
      src: index.html.j2
      dest: /home/vagrant/index.html
  - name: install apache
    community.docker.docker_container:
      name: apache
      image: httpd:2.4.57-alpine3.18
      state: started
      ports:
        - "80:80"
      volumes:
        - /home/vagrant/index.html:/usr/local/apache2/htdocs/index.html