- name: "Apache installation using docker"
  hosts: prod
  become: true
  pre_tasks:
  - name: install epel release
    yum:
      name: epel-release
      state: latest
    when: ansible_facts['os_family'] == "Redhat"
  - name: install docker
    ansible.builtin.package:
      name: "{{ item }}"
    loop:
      - python-pip
      - python-setuptools
      - python-virtualenv
      - docker
      - python-docker-py
  - name: start docker engine
    ansible.builtin.systemd:
      state: started
      name: docker
  tasks:
  - name: install apache
    community.docker.docker_container:
      name: apache
      image: httpd:2.4.57-alpine3.18
      state: started
      ports:
        - "80:80"